name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # You can specify a version like '1.0.5' if needed

      # 3. Build the Hugo site
      - name: Build Site
        run: hugo --minify

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Optional: Add a custom domain
          # cname: yourdomain.com